# Generated by Django 6.0.7 on 2026-07-19 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_report_options_report_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apisetting',
            options={'verbose_name': 'API Setting', 'verbose_name_plural': 'API Settings'},
        ),
        migrations.AlterModelOptions(
            name='barang',
            options={'ordering': ['nama_barang'], 'verbose_name': 'Barang', 'verbose_name_plural': 'Barang'},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'Company Profile', 'verbose_name_plural': 'Company Profiles'},
        ),
        migrations.AlterModelOptions(
            name='kustomer',
            options={'ordering': ['nama_kustomer'], 'verbose_name': 'Kustomer', 'verbose_name_plural': 'Kustomer'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['nama_supplier'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Activity', 'verbose_name_plural': 'User Activities'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='weightdata',
            options={'ordering': ['-created_at'], 'verbose_name': 'Weight Data', 'verbose_name_plural': 'Weight Data'},
        ),
    ]
