# Generated by Django 5.2 on 2026-07-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_apisetting_options_alter_barang_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
