# Generated by Django 5.2 on 2026-07-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_companyprofile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file_path',
            field=models.TextField(blank=True, help_text='Path ke file snapshot atau base64'),
        ),
    ]
